-- phpMyAdmin SQL Dump
-- version 2.11.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 20, 2009 at 07:12 PM
-- Server version: 5.0.45
-- PHP Version: 5.2.3-1ubuntu6.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `tienda`
--

-- --------------------------------------------------------

--
-- Table structure for table `camisetas`
--

DROP TABLE IF EXISTS `camisetas`;
CREATE TABLE IF NOT EXISTS `camisetas` (
  `id` int(11) NOT NULL auto_increment,
  `clave` varchar(255) NOT NULL,
  `nombre` varchar(255) default 'sin nombre',
  `texto` text,
  `modelos` text,
  `fotos` text,
  `categorias` text,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=38 ;

--
-- Dumping data for table `camisetas`
--

INSERT INTO `camisetas` (`id`, `clave`, `nombre`, `texto`, `modelos`, `fotos`, `categorias`) VALUES
(26, '', 'ELLOS (mini-cd) (Sistema de Monos + Hola Por QuÃ©)', 'Banda sonora original del camisetÃ¡logo ''te amo / te desamo'' de Hola Por QuÃ©. Incluye la canciÃ³n ''ellos'', original de Sistema de Monos, el videoclip de la canciÃ³n, realizado por Hola Por QuÃ©, y la pÃ¡gina web de Hola Por QuÃ©. Todo diseÃ±ado, producido y serigrafiado por Hola Por QuÃ©. AÃ±o de publicaciÃ³n: 2007.\r\nwww.sistemademonos.com', 'mini-cd Ellos,50,4', 'http://www.holaporque.com/vendidos/fotos/minicd-ellos.jpg', 'cd\r\nte amo / te desamo'),
(6, '', 'VOTA', 'Esto ejemplifica claramente el famoso dicho que dice que las moscas van a la mierda. \r\nQue ver peleas de gallos cada 4 aÃ±os y apostar por uno no creemos que sea lo que ellos llaman poder del pueblo, etimolÃ³gicamente hablando. O tal vez sea que esto es una demo de la democracia, es como la versiÃ³n demo de un programa de ordenador que sÃ³lo te deja hacer ciertas cosas. Pues entonces tendremos que esperar a que salga la versiÃ³n pro.', 'bÃ¡sica chico naranja tostado S,3,20\r\nbÃ¡sica chico naranja tostado M,5,20\r\nbÃ¡sica chico negra S,1,20\r\nbÃ¡sica chico negra M,2,20\r\nbÃ¡sica chico negra L,1,20\r\nbÃ¡sica chico negra XL,1,20', 'http://www.holaporque.com/vendidos/fotos/vota-chico-camiseta_basica-texas-1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/vota-chico-camiseta_basica-texas-2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/vota-chico-camiseta_basica-texas-3.jpg', 'camisetas\r\nchico'),
(7, '', 'NAVIDAD NO.', 'Esto es una copia de aquel famoso logo de los 90 de ''drogas no.''. Nos parece que las drogas y la navidad es algo que produce el mismo efecto en gran cantidad de personas. la navidad es como una droga legal. Que si te duele la cabeza, pues te cantas unos villancicos y pones a un reciÃ©n nacido encima del taquillÃ³n de la entrada; luego te vas a comprar muchas cosas que no necesitas, y contribuyes a la tala indiscriminada de abetos que dentro de un mes acabarÃ¡n en el cubo de basura, cuÃ¡ndo aÃºn estarÃ¡n vivos. Pero a parte de esto, queremos seÃ±alar que no estamos en contra del turrÃ³n, para nada. Y no entendemos porque no los venden el resto del aÃ±o, que saben igual.', 'bÃ¡sica chico negra XL,1,25\r\n', 'http://www.holaporque.com/vendidos/fotos/navidad_no.-chico-camiseta_basica-negro.jpg', 'camisetas\r\nchico'),
(8, '', 'LA GENTE ES BOBA', 'Esta es la momia del Coronel Giuliano, que estÃ¡ en el convento de los capuchinos de Palermo. El tipo este despuÃ©s de una vida de guerras, andanzas y penurias, va y se muere, lo embalsaman y lo exponen a los turistas que nos dejamos caer por allÃ­ para que le echemos unas fotos. Esta es su reflexiÃ³n despuÃ©s de unos pocos siglos de cuelgue en la pared: la gente es boba.\r\nTambiÃ©n era el pensamiento mÃ¡s recurrente de la Alba cuando trabajaba en el Sandwich and Friends de Barcelona. \r\n', 'No hay existencias,0,25\r\n', 'http://www.holaporque.com/vendidos/fotos/la_gente_es_boba-chica-basica-rojo.jpg', 'camisetas\r\nchico'),
(9, '', 'EN ESTE PAÃS DE MIERDA SOLO HUELE A COLONIA', 'QuerÃ­a hacer una comparaciÃ³n entre la mierda y la colonia. Generalmente todos se preocupan de oler bien, de las apariencias, de su imagen exterior. El entorno no les preocupa. Corren perfumados por el estercolero. Y mientras van fumando cigarrillos que guardan en pitilleras de oro. Y se llenan de alhajas. QuizÃ¡s estÃ© exagerando, pero algo asÃ­ querÃ­a decir, vaya.', 'bÃ¡sica chico rojo oscuro S,1,25\r\nbÃ¡sica chico rojo oscuro XL,3,25', 'http://www.holaporque.com/vendidos/fotos/en_este_pais_de_mierda_solo_huele_a_colonia-chico-camiseta_basica-texas-1.jpg', 'camisetas\r\nchico'),
(10, '', 'Â¡CAGA!', 'Â¡Ah!, esta es una de mis favoritas. La niÃ±a diciendo a su perrito: Â¡Caga!. Â¡QuÃ© mejor ejemplo de dominaciÃ³n!. Como si fuese un peluche. Lo peor es que cuando las niÃ±as y los niÃ±os se hacen mayores siguen teniendo a los perritos enjaulados entre cuatro paredes. Eso sÃ­ que es querer a los animales, igual que los quieren los toreros.', 'bÃ¡sica chico amarillo pÃ¡lido L,1,25', 'http://www.holaporque.com/vendidos/fotos/caga-chico-camiseta_basica-azul_cielo.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/caga-chico-camiseta_basica-amarillo_palido.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/caga-chica-camiseta_entallada_de_chica-azul_cielo.jpg', 'camisetas\r\nchico'),
(11, '', 'LA GALLINA DAÃ‘INA', 'Es simplemente la gracia de las dos palabras, gallina y daÃ±ina. Nada, un juego de palabras. TambiÃ©n la cosa de poner a la gallina como un animal peligroso que fuese a acabar con la humanidad. Una amenaza que se gesta en los corrales. Pero que son imaginaciones nuestras na mÃ¡s.', 'bÃ¡sica chico verde lima S,3,25', 'http://www.holaporque.com/vendidos/fotos/la_gallina_danina-chico-camiseta_basica-verde_lima-1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/la_gallina_danina-chico-camiseta_basica-verde_lima-2.jpg', 'camisetas\r\nchico'),
(12, '', 'PÃJAROS', 'Esto, como os supondrÃ©is, estÃ¡ inspirado en la peli de los pÃ¡jaros de Hitchcock. La cuestiÃ³n es que una vez hace mil aÃ±os estÃ¡bamos pensando en disfrazarnos de Tippi Hedren , la prota del filme, y llevar muchos pÃ¡jaros negros de cartulina colgando de la ropa. Al final nos disfrazamos de planta carnÃ­vora, pero la idea quedÃ³ para esta bonita estampa, que todo hay que decirlo nos la han copiado mogollÃ³n (hemos tenido hasta pleitos legales) y hasta la han puesto de moda (el otro dÃ­a vi unas bragas con pÃ¡jaros en una cadena de Ã©sas que luchan por diferenciarnos a los unos de los otros vistiÃ©ndonos a todos igual). La Ãºltima noticia es que mi hermana la ha visto copiada en una tienda perdida de Hiroshima.', 'bÃ¡sica chico roja XS,3,30\r\nbÃ¡sica chico roja L,3,30\r\nbÃ¡sica chico azul Ã­ndigo M,2,30\r\nbÃ¡sica chico azul Ã­ndigo L,1,30', 'http://www.holaporque.com/vendidos/fotos/pajaros-chica-camiseta_basica-roja-1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/pajaros-chica-camiseta_basica-azul_cielo.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/pajaros-chico-camiseta_basica-azul_indigo-1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/pajaros-chico-chica-camiseta_basica-azul_indigo-azul_cielo.jpg', 'camisetas\r\nchico'),
(13, '', 'KAOS EN LA CIUDAD', 'Esto no va de que es una tÃ­a que persigue a la gente de las ciudades con su gran cerebro, como si fuese un monstruo sanguinario. En realidad el protagonista es el cerebro, es el monstruo sanguinario que provoca el pÃ¡nico entre la poblaciÃ³n, con sus peligrosos pensamientos. La gente corre despavorida porque es muy peligroso, porque ellos no tienen cerebro y estÃ¡n asustados de lo que les pueda hacer. Lo de que las piernas sean de tÃ­a sÃ³lo es porque quedaba mÃ¡s bonito para la escena.', 'chico gris zinc s,3,40\r\nchico gris zinc m, 3, 40\r\nchico gris zinc l, 3, 40', 'http://www.holaporque.com/vendidos/fotos/kaos_en_la_ciudad-chica-camiseta_bicolor-granate_jaspeado-granate-1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/kaos_en_la_ciudad-chica-camiseta_bicolor-granate_jaspeado-granate-2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/kaos_en_la_ciudad-chico-camiseta_basica-gris_jaspeado-1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/kaos_en_la_ciudad-chico-camiseta_basica-gris_jaspeado-2.jpg', 'camisetas\r\nLapidalandia'),
(14, '', 'NO SOY TU PUTA', 'No habla precisamente de la pederastia. Al menos al hacerla no pensamos en eso. Y no estaba tan de moda. Simplemente es chocante oir a una niÃ±a decir ''no soy tu puta'', con su voz inocente y virginal.', 'chico - camiseta bÃ¡sica - verde lima - XL,1,25', 'http://www.holaporque.com/vendidos/fotos/no_soy_tu_puta-chico-camiseta_basica-verde_lima_y_rosa.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/no_soy_tu_puta-general.jpg', 'camisetas\r\nchico'),
(15, '', 'LAPIDALANDIA (mini-cd) (Hadidas ApÃ³stol + Hola Por QuÃ©)', '     Este mini-cd de ediciÃ³n limitada, es una colaboraciÃ³n entre Hola Por QuÃ© y Hadidas ApÃ³stol.\r\nContiene la canciÃ³n ''Lapidalandia'', de Hadidas ApÃ³stol, que ilustra musicalmente el camisetÃ¡logo\r\nLapidalandia de Hola Por QuÃ©.\r\n     AdemÃ¡s hay una pista cd-rom con el videoclip de la canciÃ³n y la pÃ¡gina web de Hola Por quÃ©.   \r\n     El mini-cd y la funda de cartÃ³n los ha serigrafiado Hola Por QuÃ©. AÃ±o de publicaciÃ³n: 2005. 2Âª ediciÃ³n: 2007.', 'mini-cd Lapidalandia,50,4', 'http://www.holaporque.com/vendidos/fotos/mini-cd-Lapidalandia-portada.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/mini-cd-Lapidalandia-contra.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/mini-cd-Lapidalandia-mini-cd.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/mini-cd-Lapidalandia-general.jpg', 'cd\r\nLapidalandia'),
(16, '', 'TE AMO', 'TÃ­pica sensaciÃ³n esa del amor de sentir cosquillas por dentro. Como el revolotear de unas mariposas. Como de haber comido mariposas vivas y sentirlas agitarse por dentro de uno mismo. Y sonreir como murmurando. Y sentir que tambiÃ©n se es mariposa dentro de sÃ­.', 'chico - camiseta bÃ¡sica - grafito - S,1,36\r\nchica - camiseta de tirantes - negro - S,1,36\r\nchica - camiseta de tirantes - negro - M,2,36\r\nchica - camiseta de tirantes - negro - L,3,36\r\nchica - camiseta de tirantes - acero - S,1,36\r\nchica - camiseta de tirantes - acero - M,5,36\r\nchica - camiseta de tirantes - acero - L,1,36\r\n', 'http://www.holaporque.com/vendidos/fotos/te_amo-chico-camiseta_pico-grafito.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_amo-chica-camiseta_raglan-negra.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_amo-chica-vestido_T-negro.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_amo-chica-tirantes-acero.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(17, '', 'TE ABRAZO', 'La segunda fase del amor contempla el contacto fÃ­sico. Cuando uno se deja de sentir mariposa, comienza a ser en tanto que el ser al que ama le hace ser.', 'chico - camiseta pico - negra - L,0,36\r\nchica - camiseta de tirantes - negra - M,0,36', 'http://www.holaporque.com/vendidos/fotos/te_abrazo-chica-tirantes-negra.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_abrazo-chico-basica-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_abrazo-chico-basica-negra_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(18, '', 'CHORRETÃ“N', 'AquÃ­ ya es cuando se confirman el cuerpo y la mente en su empecinamiento por querer llegar a ser algo metafÃ­sico. Unos breves instantes que elevan el censo de mariposas en varios kilÃ³metros a la redonda, que las envuelven en pequeÃ±os estÃ³magos y que nos los introducen todos a la vez en nuestro pequeÃ±o cerebro.', 'chico bÃ¡sica negra M,1,32\r\n', 'http://www.holaporque.com/vendidos/fotos/chorreton-chico-basica-grafito_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/chorreton-chico-basica-grafito_2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/chorreton-chico-basica-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/chorreton-chico-basica-negra_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchico'),
(23, '', 'TE ATO', 'DespuÃ©s de dormir comienzan los problemas. Los brazos que les unÃ­an se transforman en cuerdas. Se empiezan a sentir amordazados por el otro. Y la tan anhelada uniÃ³n en un solo ser se ve interrumpida por el deseo de realizarse como individuo.', 'chico - camiseta bÃ¡sica - grafito - M,1,40\r\nchico - camiseta bÃ¡sica - negra - M,1,40\r\nchico - camiseta bÃ¡sica - zinc - M,2,40\r\nchica - camiseta T - M,1,40\r\nchica - camiseta T - L,6,40', 'http://www.holaporque.com/vendidos/fotos/te_ato-chica-camiseta_T-negra.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_ato-chica-vestido_T-negro.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_ato-chico-basica-zinc.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_ato-chico-basica-negra.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(21, '', 'VOLCÃN', 'El deseo, el sexo, los lÃ­quidos, esto es lo mejor que hay. Hombres heterosexuales del mundo: Â¡a las mujeres nos encanta follar!, pero para nosotras es una cuestiÃ³n de comunicaciÃ³n y ritmo, no de mete-saca. SÃ³lo hace falta ponerle interÃ©s, investigar, hablar y probar. No sabÃ©is lo que os perdÃ©is. Intentadlo, por favorâ€¦', 'chica - camiseta raglÃ¡n S,0,35\r\nchica - camiseta raglÃ¡n M,2,35', 'http://www.holaporque.com/vendidos/fotos/volcan-chica-vestido_T-negro_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/volcan-chica-camiseta_raglan-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/volcan-chica-vestido_T-negro_2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/volcan-chica-camiseta_raglan-negra_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchica'),
(22, '', 'DORMIR CONTIGO', 'Este es el primer paso de todos los procesos del amor, donde comienza la vida real. Hasta ahora todo ha sido idealizado y es en el reposo donde se pueden apreciar los detalles ajenos. Empieza la era de la convivencia, aunque sea tumbados y mirando al techo.\r\n', 'chico - camiseta bÃ¡sica - negra - M,0,36\r\nchica - camiseta de tirantes - negra - S,4,40\r\nchica - camiseta de tirantes - negra - M,4,40\r\n', 'http://www.holaporque.com/vendidos/fotos/dormir_contigo-chico-basica-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/dormir_contigo-chico-basica-negra_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchico'),
(24, '', 'TE DESAMO', 'Tantos procesos tan complicados se nos atragantan y nos sentimos llenos de nidos de clavos, revoloteando en un campo de amapolas, golpeÃ¡ndose contra las paredes de nuestro estÃ³mago. La racionalidad en su nuevo estado. Se acabÃ³ al amor. En este paso los dos seres no suelen estar al mismo nivel, por eso uno siente clavos y el otro indigestiÃ³n.', 'chico - camiseta pico - acero - M,2,32\r\nchico - camiseta pico - acero - L,1,32\r\nchica - camiseta de tirantes - acero - L,1,32', 'http://www.holaporque.com/vendidos/fotos/te_desamo-chica-tirantes-acero_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_desamo-chica-tirantes-acero_2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_desamo-chico-camiseta_pico-acero_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/te_desamo-chico-camiseta_pico-acero_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(25, '', 'FINAL FELIZ', 'Nunca falla y aquÃ­ no hay riesgos de malentendidos. Este paso suele disfrutarlo mÃ¡s el que no siente el desamor, pues aÃºn estando todavÃ­a en el primer paso, el de las mariposas, y aÃºn teniendo como correspondencia el vacÃ­o, puede llenarse Ã©l solito del premio de consolaciÃ³n del amor. ', 'no hay existencias,0,25', 'http://www.holaporque.com/vendidos/fotos/final_feliz-chica-camiseta_raglan-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/final_feliz-chica-camiseta_raglan-negra_2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/final_feliz-chico-basica-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/final_feliz-chico-basica-negra_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(27, '', 'PÃJAROS (te amo / te desamo)', '', 'chico - camiseta bÃ¡sica - grafito - M,0,36\r\nchica - camiseta de tirantes - acero - S,1,36\r\nchica - camiseta de tirantes - acero - M,1,36', 'http://www.holaporque.com/vendidos/fotos/pajaros-te_amo-te_desamo-chica-tirantes-acero_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/pajaros-te_amo-te_desamo-chica-tirantes-acero_2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/pajaros-te_amo-te_desamo-chico-basica-zinc_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/pajaros-te_amo-te_desamo-chico-basica-zinc_2.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(28, '', 'CORAZÃ“N (te amo / te desamo)', 'Cuando era pequeÃ±a me gustaba el cuadro del caballero de la mano en el pechoâ€¦para mÃ­ lo que tocaba con su alargada mano era el corazÃ³n, no veÃ­a la cruz, veÃ­a un corazÃ³n rojo. Mostrar el corazÃ³n me parece desnudarse y de gente valiente. Me gusta.\r\nAlguna vez que he visitado un hospital la cami ha llamado mucho la atenciÃ³n al personal mÃ©dicoâ€¦\r\n', 'chico - camiseta bÃ¡sica - negra - M,0,36\r\nchica - camiseta raglÃ¡n - negra - M,0,36', 'http://www.holaporque.com/vendidos/fotos/corazon-te_amo-te_desamo-chico-camiseta_pico-negra_1.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/corazon-te_amo-te_desamo-chico-camiseta_pico-negra_2.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/corazon-te_amo-te_desamo-chico-camiseta_pico-negra_3.jpg', 'camisetas\r\nte amo / te desamo\r\nchico\r\nchica'),
(29, '', 'REBAÃ‘O DE CEREBROS', 'Esto es solamente una contradicciÃ³n. Se supone que los cerebros piensan y que los rebaÃ±os simbolizan la anulaciÃ³n del individuo. En las ciudades se ven muchos individuos en potencia, personas independientes, todas distinguibles. Sin embargo suelen acabar agrupadas para poder darse valor a sÃ­ mismas, pastando en el asfalto. Y terminan por ser arrebaÃ±adas en rebaÃ±os que forman parte de otros rebaÃ±os mÃ¡s grandes y asÃ­ sucesivamente.', 'chico - camiseta bÃ¡sica - gris grafito - S,1,30\r\nchico - camiseta bÃ¡sica - gris grafito - M,1,30\r\nchico - camiseta bÃ¡sica - gris grafito - L,1,30\r\nchico - camiseta bÃ¡sica - naranja - S,1,30\r\nchico - camiseta bÃ¡sica - naranja - M,4,30\r\nchico - camiseta bÃ¡sica - naranja - L,1,30\r\nchica - camiseta raglÃ¡n - naranja - M,1,36', 'http://www.holaporque.com/vendidos/fotos/rebano_de_cerebros-chico-basica-naranja.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/rebano_de_cerebros-chico-basica-gris_jaspeado.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/rebano_de_cerebros-chica-camiseta_raglan-gris_grafito.jpg', 'camisetas\r\nLapidalandia\r\nchico\r\nchica'),
(30, '', 'LLUEVEN COCHES', '''''[...] y llegarÃ¡ el dÃ­a en que lluevan coches y los mares [...]'''' (San Mateo, capÃ­tulo 45, versÃ­culo 24).\r\nNo me extraÃ±a. Se veÃ­a venir. No hay mÃ¡s que asomarse a las ventanas para ver esa masa informe que se arrastra por las calles de nuestro planeta, que parecen reproducirse sin fin, y cada vez mÃ¡s grandes y mÃ¡s fortalecidos. Hay tanta saturaciÃ³n que los coches acabarÃ¡n evaporÃ¡ndose y ese humo tÃ³xico se condensarÃ¡ y los coches volverÃ¡n a caer sobre nuestras casas y sobre nuestras gasolineras.', 'chico - camiseta bÃ¡sica - gris grafito - L,1,30\r\nchico - camiseta bÃ¡sica - verde fosforito - S,1,30\r\nchica - camiseta raglÃ¡n - verde fosforito - M,1,36', 'http://www.holaporque.com/vendidos/fotos/llueven_coches-chico-basica-naranja.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/llueven_coches-chica-camiseta_raglan-naranja.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/llueven_coches-chico-basica-verde_fosforito.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/llueven_coches-chico-basica-gris_grafito.jpg', 'camisetas\r\nLapidalandia\r\nchico\r\nchica'),
(31, '', 'TRAGALDABAS', 'Ya no hacemos ciudades. Ahora son ellas las que nos crean a nosotros, dÃ¡ndonos una identidad. Por eso pueden aplastarnos o decidir si podemos cruzar los pasos de cebra sin ser atropellados por los coches, que son sus perros amaestrados, esperando al acecho en cada semÃ¡foro en rojo.', 'chico - camiseta bÃ¡sica - naranja - S,1,30\r\nchico - camiseta bÃ¡sica - naranja - M,2,30\r\nchico - camiseta bÃ¡sica - naranja - L,1,30\r\nchica - camiseta raglÃ¡n - gris grafito - M,1,36', 'http://www.holaporque.com/vendidos/fotos/tragaldabas-chico-basica-naranja.jpg', 'camisetas\r\nLapidalandia\r\nchico\r\nchica'),
(32, '', 'APARTAMENTO PARA TRES', 'Si buscamos piso es fÃ¡cil que nos encontremos con anuncios como el que aquÃ­ hemos seleccionado: ''C/ Fuencarral. Apto., para entrar, muy bonito, luminosos, finca preciosa, rehab., no ascensor, no ascensor, ideal pareja. 216.024 â‚¬''. Â¿CuÃ¡ntos aÃ±os debemos de vivir para pagar esto?. Tal vez para alguien que crea en la reencarnaciÃ³n esto no sea ningÃºn problema. Para poder habitar una casa vamos a tener que disfrazarnos de bolsas de basura, y tendremos que resignarnos a vivir encogidos en 1 metro cuadrado, algo baratito, un zulo en el que moriremos secuestrados por el mercado inmobiliario. Hemos sido bastante optimistas con esta camiseta.', 'chico - camiseta bÃ¡sica - grafito - S,3,30\r\nchico - camiseta bÃ¡sica - grafito - M,2,30\r\nchico - camiseta bÃ¡sica - grafito - L,1,30\r\nchico - camiseta bÃ¡sica - naranja - M,7,30\r\nchica - camiseta raglÃ¡n - naranja - M,1,36', 'http://www.holaporque.com/vendidos/fotos/apartamento_para_tres-chica-camiseta_raglan-verde_fosforito.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/apartamento_para_tres-chica-camiseta_raglan-gris_grafito.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/apartamento_para_tres-chico-basica-verde_fosforito.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/apartamento_para_tres-chico-basica-gris_jaspeado.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/apartamento_para_tres-chica-camiseta_raglan-naranja.jpg', 'camisetas\r\nLapidalandia\r\nchico\r\nchica'),
(37, '', 'EL GERNIKA DE PICACHU', 'Hemos realizado una versiÃ³n especial de este famoso cuadro que pintÃ³ uno que ahora estÃ¡ muerto, y lo hemos estampado en bolsas y camisetas, ademÃ¡s de unas chapas que hemos hecho con partes del dibujo. Aunque sigue habiendo guerras, creemos que la civilizaciÃ³n tambiÃ©n tiene vencedore y vencidos, y eso es lo que hemos querido reflejar aquÃ­. Hay trabajadores explotados, constructores muertos amasando billetes, gente que no quiere ver nada alumbrando con linternas que dan oscuridad, inmobiliarios pisando contratos, ... en fin, todo un espectÃ¡culo. Y tambiÃ©n hay un Picachu sustituyendo a la paloma de la paz del cuadro original.\r\nSerigrafÃ­a a 5 colores disponible en papel blanco o negro. Dimensiones: 60 x 33 cm. Va dentro de una carpeta. 1Âª ediciÃ³n de 50 ejemplares.', 'blanco,12,65\r\nnegro,14,65', 'http://www.holaporque.com/vendidos/fotos/el_Gernika_de_Picachu-papel_blanco-Hola_Por_Que.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/el_Gernika_de_Picachu-papel_blanco-detalle1-Hola_Por_Que.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/el_Gernika_de_Picachu-papel_blanco-detalle2-Hola_Por_Que.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/el_Gernika_de_Picachu-papel_blanco-detalle3-Hola_Por_Que.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/el_Gernika_de_Picachu-papel_blanco-detalle4-Hola_Por_Que.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/el_Gernika_de_Picachu-carpeta-Hola_Por_Que.jpg', 'obra grÃ¡fica'),
(34, '', 'EL PATRIARCA DE LA CALLE ENCARNACIÃ“N (Hadidas ApÃ³stol)', '3Âº disco de este conjunto musico-vocal afincado en Palencia, aunque este trabajo fue grabado por tandas entre Salamanca, Madrid y Palencia, con la ayuda de los estudios portÃ¡tiles Alma CadÃ¡ver, osease, un ordenador que iba de una casa a otra. El estilo digamos que es raro, algo asÃ­ como uno tocando la guitarra espaÃ±ola, otro dando golpes a un cajÃ³n flamenco y otro chillando. Aunque a veces se chilla menos, a veces hay guitarras elÃ©ctricas, a veces cajas de ritmos, cachos de grabaciones de la tele, una chica cantando una canciÃ³n,... y a veces hay mÃºsica. TambiÃ©n incluye el videoclip de la canciÃ³n ''Â¿quÃ© hay?''. AÃ±o de publicaciÃ³n: 2003.\r\nwww.hadidasapostol.holaporque.com', 'cd,34,4', 'http://www.holaporque.com/vendidos/fotos/HADIDAS_APOSTOL-el_patriarca_de_la_calle_encarnacion-portada.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/HADIDAS_APOSTOL-el_patriarca_de_la_calle_encarnacion-contra.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/HADIDAS_APOSTOL-el_patriarca_de_la_calle_encarnacion-cd.jpg\r\nhttp://www.holaporque.com/vendidos/fotos/HADIDAS_APOSTOL-el_patriarca_de_la_calle_encarnacion-paginas_centrales.jpg', 'cd'),
(35, '', 'BESOS', 'Hay 6 modelos distintos disponibles en dos versiones: blancas y negras.', 'blanco,13,2\r\nnegro,24,2', 'http://www.holaporque.com/vendidos/fotos/chapas-besos-te_amo-te_desamo-6_modelos.jpg', 'chapas\r\nte amo / te desamo'),
(36, '', 'CUCARACHAS', 'Las pobres cucarachas sÃ³lo quieren alimentarse y reproducirse tranquilamente. No son malas. La maldad es algo que se han inventado los humanos. Y no son asquerosas. Porque la inmundicia en la que viven es la que les proporcionamos nosotros. Desinteresadamente. Por eso queremos hacer una reivindicaciÃ³n de la cucaracha como animal de compaÃ±Ã­a, porque solo ellas saldrÃ¡n airosas de las bombas nucleares, alimentÃ¡ndose y reproduciÃ©ndose delante de los fragmentos de nuestros cuerpos con total naturalidad.', 'madre con hijo,20,1\r\n69,20,1\r\nel hijo perdido,20,1', 'http://www.holaporque.com/vendidos/fotos/chapas-cucarachas-Lapidalandia-10_modelos.jpg', 'chapas\r\nLapidalandia');

-- --------------------------------------------------------

--
-- Table structure for table `pedidos`
--

DROP TABLE IF EXISTS `pedidos`;
CREATE TABLE IF NOT EXISTS `pedidos` (
  `id` int(11) NOT NULL auto_increment,
  `usuarioNombre` varchar(255) NOT NULL default 'sin nombre',
  `usuarioDireccion` varchar(255) default 'sin direcciÃ³n',
  `usuarioTelefono` varchar(255) default 'sin telefono',
  `usuarioEmail` varchar(255) default 'sin email',
  `usuarioComentario` text,
  `fecha` datetime NOT NULL,
  `estado` varchar(50) NOT NULL default 'sin estado',
  `lineasPedido` text,
  `gastosEnvio` int(11) default '0',
  `total` int(11) default '0',
  `subtotal` int(11) NOT NULL default '0',
  `esBroma` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=82 ;

--
-- Dumping data for table `pedidos`
--

INSERT INTO `pedidos` (`id`, `usuarioNombre`, `usuarioDireccion`, `usuarioTelefono`, `usuarioEmail`, `usuarioComentario`, `fecha`, `estado`, `lineasPedido`, `gastosEnvio`, `total`, `subtotal`, `esBroma`) VALUES
(53, 'Fernando GuillÃ©n', 'Calle NicolÃ¡s Morales 38, 3-8, Madrid, EspaÃ±a', '669477485', 'fguillen.mail@gmail.com', 'fasfdsd', '2008-03-01 21:07:21', 'sin estado', '5,ELLOS (mini-cd),mini-cd Ellos,1,4\n5,ELLOS (mini-cd),mini-cd Ellos,1,4\n', 10, 18, 8, 0),
(54, 'safd', 'asd', 'sdaf', 'asd', 'asd', '2008-03-01 21:07:46', 'sin estado', '5,ELLOS (mini-cd),mini-cd Ellos,1,4\n', 10, 14, 4, 0),
(55, 'sad', 'asdasd', 'asd', 'asdasd', 'asd', '2008-03-01 21:08:32', 'sin estado', '5,ELLOS (mini-cd),mini-cd Ellos,1,4\n', 10, 14, 4, 1),
(56, 'El nano', 'Calle NicolÃ¡s Morales 38, 3-8, Madrid, EspaÃ±a', 'mi telÃ©fono', 'fguillen.mail@gmail.com', 'asdf', '2008-03-01 20:18:42', 'sin estado', '5,ELLOS (mini-cd),mini-cd Ellos,1,4\n', 10, 14, 4, 1),
(57, 'gsd', 'sdg', 'fasdf', 'fguillen.mail@gmail.com', 'asd', '2008-03-01 20:23:22', 'sin estado', '13,KAOS EN LA CIUDAD,,,0\n', 10, 10, 0, 1),
(58, '', '', '', 'fguillen.mail@gmail.com', '', '2008-03-01 21:17:52', 'sin estado', '6,VOTA,b?sica chico naranja tostado L,2,0\n6,VOTA,b?sica chico naranja tostado L,2,0\n', 10, 10, 0, 1),
(59, 'plin', 'plon', 'claro', 'vicius@holaporque.com', 'hombre', '2008-03-01 22:03:36', 'sin estado', '13,KAOS EN LA CIUDAD,revisar S,1,200\n5,ELLOS (mini-cd),mini-cd Ellos,8,4\n9,EN ESTE PAÃS DE MIERDA SOLO HUELE A COLONIA,bÃ¡sica chico rojo oscuro XL,3,25\n', 10, 317, 307, 1),
(60, 'fernandigo', 'calle', '666', 'vicius@holaporque.com', 'a ver si llegan los pedidos.', '2008-03-13 17:39:39', 'sin estado', '6,VOTA,bÃ¡sica chico naranja tostado S,1,20\n', 10, 30, 20, 1),
(61, 'JUAN TERAN ', 'AV K SECTOR 5 BOCAS CASA #128', '02643711563', 'juanym_1@hotmail.com', '', '2008-04-17 03:23:44', 'sin estado', '6,VOTA,bÃ¡sica chico naranja tostado S,3,20\n', 10, 70, 60, 0),
(62, 'JUAN TERAN ', 'AV K SECTOR 5 BOCAS CASA #128', '02643711563', 'juanym_1@hotmail.com', '', '2008-04-22 12:51:27', 'sin estado', '8,LA GENTE ES BOBA,bÃ¡sica chico roja S,2,25\n11,LA GALLINA DAÃ‘INA,bÃ¡sica chico verde lima S,3,25\n', 10, 135, 125, 0),
(63, 'JUAN TERAN ', 'AV K SECTOR 5 BOCAS CASA #128', '02643711563', 'juanym_1@hotmail.com', '', '2008-04-22 12:53:11', 'sin estado', '11,LA GALLINA DAÃ‘INA,bÃ¡sica chico verde lima S,3,25\n12,PÃJAROS,bÃ¡sica chico roja XS,2,30\n', 10, 145, 135, 0),
(64, 'Cristina Barahona', 'Carril Ruiperez nÂº13, 2ÂºB, 30007 ', '', '', '', '2008-05-23 18:12:09', 'sin estado', '16,TE AMO,chica - camiseta raglÃ¡n - negro - M,2,36\n', 10, 82, 72, 0),
(65, 'Cristina Barahona, ', 'Carril ruiperez nÂº13, 2ÂºB, 30007 Murcia', '619827400', 'ondoloegin@hotmail.com', '', '2008-05-23 18:13:39', 'sin estado', '16,TE AMO,chica - camiseta raglÃ¡n - negro - M,2,36\n', 10, 82, 72, 0),
(66, 'Alba Ruiz', 'c/ Virgen de Ãfrica,1 , 4Âº 1Âº', '607372069', 'alba_go@yahoo.es', '', '2008-05-28 12:35:05', 'sin estado', '8,LA GENTE ES BOBA,bÃ¡sica chico roja M,1,25\n', 10, 35, 25, 0),
(67, '', '', '', '', '', '2008-06-08 23:15:16', 'sin estado', '26,ELLOS (mini-cd) (Sistema de Monos + Hola Por QuÃ©),mini-cd Ellos,1,4\n', 10, 14, 4, 0),
(68, '', '', '', '', '', '2008-06-18 14:00:57', 'sin estado', '6,VOTA,bÃ¡sica chico naranja tostado S,2,20\n31,TRAGALDABAS,chico - camiseta bÃ¡sica - naranja - L,1,30\n', 10, 80, 70, 0),
(69, 'a', 'a', '', 'a@a.es', 'a', '2008-06-18 14:01:22', 'sin estado', '6,VOTA,bÃ¡sica chico naranja tostado S,2,20\n31,TRAGALDABAS,chico - camiseta bÃ¡sica - naranja - L,1,30\n', 10, 80, 70, 1),
(70, '', '', '', '', '', '2008-06-21 22:16:47', 'sin estado', '11,LA GALLINA DAÃ‘INA,bÃ¡sica chico verde lima S,1,25\n', 10, 35, 25, 1),
(71, 'Sergio PÃ©rez', 'C/ Utrillas, 8 - piso 14B', '676203314', 'ana_rojo@terra.es', 'Es un regalo para Sergio, pero la compradora soy yo, con lo que si hay algÃºn problema es mejor que os pongais en contacto conmigo(Ana) en el mail y movil que os doy. ', '2008-09-28 12:39:06', 'sin estado', '12,PÃJAROS,bÃ¡sica chico roja L,1,30\n', 10, 40, 30, 0),
(72, 'Sonia Dybdahl', 'Simensbraatveien 8, 1182 Oslo, Noruega', '(0047)41506546', 'sonia.dybdahl@gmail.colm', 'he visto la camiseta en la tienda del museo "ReÃ­na Sofia" en Madrid. Me gustaria lo comprar ahora si es posible. ', '2008-10-08 20:07:11', 'sin estado', '31,TRAGALDABAS,chico - camiseta bÃ¡sica - naranja - S,1,30\n', 10, 40, 30, 0),
(73, '', '', '', '', '', '2008-10-09 18:46:38', 'sin estado', '12,PÃJAROS,bÃ¡sica chico roja XS,1,30\n', 10, 40, 30, 0),
(74, 'Jaume Estades Amengual', 'Passeig de Cala Gamba 9, 07007 Palma de Mallorca', '687556635', 'estrany@hotmail.com', 'Sois los masca. Enviarme una cucarachitas en chapas de obsequio si puÃ© ser, como la otra vez( o algun beso). GrÃ cies', '2008-12-04 12:27:47', 'sin estado', '6,VOTA,bÃ¡sica chico naranja tostado L,1,20\n30,LLUEVEN COCHES,chico - camiseta bÃ¡sica - gris grafito - L,1,30\n', 10, 60, 50, 0),
(75, 'El nano', 'prueba', 'prueb', 'prueb', 'es una pruebaa', '2008-12-04 12:38:47', 'sin estado', '6,VOTA,bÃ¡sica chico naranja tostado S,1,20\n', 10, 30, 20, 1),
(76, '', '', '', '', '', '2009-01-14 10:16:41', 'sin estado', '26,ELLOS (mini-cd) (Sistema de Monos + Hola Por QuÃ©),mini-cd Ellos,1,4\n', 10, 14, 4, 1),
(77, 'Manolo', 'No hay', 'hola', 'hola@hola.es', 'Es una prueba', '2009-01-23 13:26:14', 'sin estado', '29,REBAÃ‘O DE CEREBROS,chico - camiseta bÃ¡sica - naranja - L,1,30\n', 10, 40, 30, 1),
(78, 'juan luis gonzalez7sauna ego', 'nicolas alkorta 3 bajo', '607260787', 'ego_fatxi@yahoo.es', 'si es posible la camiseta que sea basica y no de tirantes,negra y talla M\r\ngracias', '2009-03-29 20:29:06', 'sin estado', '16,TE AMO,chica - camiseta de tirantes - negro - M,1,36\n', 10, 46, 36, 0),
(79, 'ANA MARIA RODRIGUEZ RICO', 'C/BOGOTÃ, NÂº 5, BLOQUE 5, 4Âº B2. 41013 SEVILLA', '646578329', 'anetarico@yahoo.es', 'Hola, un par de dudas: en el listado esta cami aparece con el precio de 30 euris y cuando la he echado al carro ha pasado a 36; os quedan en mÃ¡s colores para chica ademÃ¡s del gris grafito?\r\nEspero vuestros comentarios e instrucciones. Enhorabuena por vuestro trabajo y saluditos. ', '2009-05-13 18:20:00', 'sin estado', '31,TRAGALDABAS,chica - camiseta raglÃ¡n - gris grafito - M,1,36\n', 10, 46, 36, 0),
(80, 'JesÃºs Valiente', 'Plaza de Santo Angel, 1 - 06800 MÃ©rida', '655552754', 'decaocto@hotmail.com', '', '2009-07-23 13:16:22', 'sin estado', '12,PÃJAROS,bÃ¡sica chico roja L,1,30\n', 10, 40, 30, 0),
(81, 'laura bella', 'bar tupi ', '650237814', 'laura.bella@orange.fr', '', '2009-08-16 20:17:51', 'sin estado', '17,TE ABRAZO,chica - camiseta de tirantes - negra - M,1,36\n21,VOLCÃN,chica - camiseta raglÃ¡n S,1,35\n17,TE ABRAZO,chico - camiseta pico - negra - L,1,36\n', 10, 117, 107, 0);
