development:
  adapter: mysql
  database: tienda
  username: tienda
  password: tienda

test:
  adapter: mysql
  database: tienda_test
  username: root
  password:

production:
  adapter: mysql
  database: tienda
  username: tienda
  password: xxxx
  socket: /var/run/mysqld/mysqld.sock